package com.timilehinaregbesola.mathalarm.framework.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

@Database(entities = [AlarmEntity::class], version = 9, exportSchema = true)
@ConstructedBy(AlarmDatabaseConstructor::class)
abstract class AlarmDatabase : RoomDatabase() {
    abstract val alarmDatabaseDao: AlarmDao
}

/**
 * Room KMP database constructor - implementation generated by Room compiler
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AlarmDatabaseConstructor : RoomDatabaseConstructor<AlarmDatabase> {
    override fun initialize(): AlarmDatabase
}
