package com.timilehinaregbesola.mathalarm.framework.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.migration.Migration
import androidx.sqlite.SQLiteConnection
import androidx.sqlite.execSQL

@Database(entities = [AlarmEntity::class], version = 4, exportSchema = true)
@ConstructedBy(AlarmDatabaseConstructor::class)
abstract class AlarmDatabase : RoomDatabase() {
    abstract val alarmDatabaseDao: AlarmDao
}

/**
 * Room KMP database constructor - implementation generated by Room compiler
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AlarmDatabaseConstructor : RoomDatabaseConstructor<AlarmDatabase> {
    override fun initialize(): AlarmDatabase
}

/**
 * Migration from version 2 to 3 - adds title column
 */
val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL(
            """
                CREATE TABLE new_alarms (
                    alarmId INTEGER PRIMARY KEY NOT NULL,
                    hour INTEGER NOT NULL,
                    minute INTEGER NOT NULL,
                    repeat INTEGER NOT NULL,
                    daysoftheweek TEXT NOT NULL,
                    ison INTEGER NOT NULL,
                    difficulty INTEGER NOT NULL,
                    tone TEXT NOT NULL,
                    vibrate INTEGER NOT NULL,
                    snooze INTEGER NOT NULL,
                    title TEXT NOT NULL DEFAULT ''
                )
            """.trimIndent()
        )
        connection.execSQL(
            """
                INSERT INTO new_alarms (alarmId, hour, minute, repeat, daysoftheweek, ison, difficulty, tone, vibrate, snooze)
                SELECT alarmId, hour, minute, repeat, daysoftheweek, ison, difficulty, tone, vibrate, snooze FROM alarms
            """.trimIndent()
        )
        connection.execSQL("DROP TABLE alarms")
        connection.execSQL("ALTER TABLE new_alarms RENAME TO alarms")
    }
}

/**
 * Migration from version 3 to 4 - adds isSaved column
 */
val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL(
            """
                CREATE TABLE new_alarms (
                    alarmId INTEGER PRIMARY KEY NOT NULL,
                    hour INTEGER NOT NULL,
                    minute INTEGER NOT NULL,
                    repeat INTEGER NOT NULL,
                    daysoftheweek TEXT NOT NULL,
                    ison INTEGER NOT NULL,
                    difficulty INTEGER NOT NULL,
                    tone TEXT NOT NULL,
                    vibrate INTEGER NOT NULL,
                    snooze INTEGER NOT NULL,
                    title TEXT NOT NULL DEFAULT '',
                    isSaved INTEGER NOT NULL DEFAULT 1
                )
            """.trimIndent()
        )
        connection.execSQL(
            """
                INSERT INTO new_alarms (alarmId, hour, minute, repeat, daysoftheweek, ison, difficulty, tone, vibrate, snooze, title)
                SELECT alarmId, hour, minute, repeat, daysoftheweek, ison, difficulty, tone, vibrate, snooze, title FROM alarms
            """.trimIndent()
        )
        connection.execSQL("DROP TABLE alarms")
        connection.execSQL("ALTER TABLE new_alarms RENAME TO alarms")
    }
}
