package com.timilehinaregbesola.mathalarm.utils.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.DE, default = false)
val DeMathAlarmStrings = Strings(
    selectAlarmPrompt = "Wähle einen Wecker aus oder erstelle einen neuen",
    closeAlarmEditor = "Bearbeitung schließen?",
    closeAlarmEditorMessage = "Nicht gespeicherte Änderungen an diesem Wecker werden verworfen.",
    discardChanges = "Änderungen verwerfen",

    mathDifficultyNames = listOf("Leicht", "Mittel", "Schwer", "Individuell"),
    mathChallengeTitle = "Matheaufgabe",
    mixedDifficulty = "Gemischte Schwierigkeit",
    mixDifficulties = "Schwierigkeitsgrade mischen",
    mathDifficulty = "Schwierigkeit",
    mathOperations = "Rechenarten",
    addition = "Addition",
    subtraction = "Subtraktion",
    multiplication = "Multiplikation",
    division = "Division",
    additionAndSubtraction = "Addition & Subtraktion",
    multiplicationAndDivision = "Multiplikation & Division",
    mathExample = "Beispiel",
    refreshExample = "Neu laden",
    applyChallenge = "Aufgaben übernehmen",
    easiestFirst = "Leichteste zuerst",
    questions = "Aufgaben",
    chooseRange = "Zahlenbereich wählen",
    checkAnswer = "Antwort prüfen",
    nextFeature = "Weiter",
    snoozeAnnouncementTitle = "Schlummern nach deinen Regeln",
    snoozeAnnouncementDescription = "Lege ein Schlummerlimit fest, wähle 1–30 Minuten oder schalte Schlummern aus. Neue Wecker starten mit 3 Schlummerphasen von je 5 Minuten. Bestehende Wecker behalten ihre Schlummerlimits.",
    snoozeAnnouncementInstructions = "Mit dem Kontrollkästchen Schlummern kannst du die Funktion schnell ein- oder ausschalten. Tippe daneben auf Bearbeiten, um Limit und Dauer zu ändern.",
    whatsNew = "Was ist neu?",
    latestFeatures = "Die neuesten Funktionen entdecken",
    gotIt = "Verstanden",
    tryFeature = "Ausprobieren",
    challengeAnnouncementTitle = "Mehr Möglichkeiten zum Aufwachen",
    challengeAnnouncementInstructions = "Füge einen Wecker hinzu oder bearbeite ihn. Tippe neben Matheaufgabe auf Bearbeiten.",
    exampleChallenge = "Beispielaufgaben",
    exampleDifficultyMix = { easy, medium -> "Leicht: $easy · Mittel: $medium" },
    challengeAnnouncementDescription = { maximum -> "Löse bis zu $maximum Aufgaben. Mische Schwierigkeitsgrade oder erstelle deine eigenen Aufgaben." },
    questionCount = ::questionCountDe,
    challengeSummary = { difficulty, count -> "$difficulty · ${questionCountDe(count)}" },
    mixedQuestionTotal = { count, maximum -> "Insgesamt ${questionCountDe(count)} · Höchstens $maximum" },
    questionProgress = { current, total -> "Aufgabe $current von $total" },
    questionCountHint = { maximum -> "Wähle 1–$maximum. Tippe auf die Zahl, um sie einzugeben." },
    difficultyQuestionLabel = { difficulty -> "Aufgaben: $difficulty" },
    decreaseQuestionCount = { label -> "Anzahl verringern: $label" },
    increaseQuestionCount = { label -> "Anzahl erhöhen: $label" },
    alarmScheduleFailed = "Wecker konnte nicht gestellt werden. Erneut speichern.",
    alarmSaveFailed = "Wecker konnte nicht gespeichert werden. Erneut versuchen.",
    alarmUpdateFailed = "Wecker konnte nicht aktualisiert werden. Erneut versuchen.",
    alarmDismissFailed = "Wecker konnte nicht beendet werden. Erneut versuchen.",
    alarmSnoozeFailed = "Wecker konnte nicht verschoben werden. Erneut versuchen.",
    incorrectAnswer = "Falsche Antwort. Erneut versuchen.",
    multipleDays = "Mehrere Tage",
    greeting = { hour ->
        when {
            hour < 12 -> "Guten Morgen"
            hour in 12..17 -> "Guten Tag"
            else -> "Guten Abend"
        }
    },
    expand = "Erweitern",
    delete = "Löschen",
    edit = "Bearbeiten",
    dateLocale = "de",
    skipAnnouncementDescription = "Pausiere den nächsten Alarm, ohne den restlichen Zeitplan zu ändern.",
    skipAnnouncementInstructions = "Klappe einen eingeschalteten Alarm auf und tippe auf Nächsten überspringen. Verfügbar für wöchentliche Alarme und Alarme mit mehreren ausgewählten Tagen.",
    skipAnnouncementUndo = "Nur der nächste Termin wird übersprungen. Wöchentliche Alarme werden in der folgenden Woche fortgesetzt; nicht wiederholende Alarme behalten ihre übrigen Termine. Tippe vor der übersprungenen Zeit auf Rückgängig. Schlummeralarme und andere Alarme bleiben geplant.",
    viewAlarms = "Alarme anzeigen",
    skipAnnouncementExample = "Probiere dieses Beispiel",
    skipNext = "Nächsten überspringen",
    skippedAlarmOn = { date -> "Übersprungen · $date" },
    undo = "Rückgängig",
    undoSkip = "Überspringen rückgängig",
    collapse = "Zusammenbruch",
    noUpcomingAlarms = "Keine bevorstehenden Alarme",
    nextAlarmText = "Nächster Alarm:",
    nextOccurrenceOn = { date -> "Nächster Termin: $date" },
    nextAlarmIn = { hours, minutes ->
        if (hours == 0 && minutes == 0) "Nächster Alarm in weniger als einer Minute"
        else "Nächster Alarm in " + listOfNotNull(
            if (hours > 0) "$hours ${if (hours == 1) "Stunde" else "Stunden"}" else null,
            if (minutes > 0) "$minutes ${if (minutes == 1) "Minute" else "Minuten"}" else null,
        ).joinToString(" ")
    },
    alarmSet = "Alarm gesetzt",
    alarmPermissionDialogConfirm = "Bestätigen",
    alarmPermissionDialogCancel = "Stornieren",
    alarmPermissionDialogText = "Diese App benötigt die Berechtigung zum Festlegen von Alarmen.",
    alarmPermissionDialogTitle = "Erforderliche Berechtigung",
    clearAlarmDialogConfirm = "Bestätigen",
    clearAlarmDialogCancel = "Stornieren",
    clearAlarmDialogText = "Sind Sie sicher, dass Sie die Alarme löschen möchten?",
    clearAlarmDialogTitle = "Klare Alarme",
    emptyAlarmList = "Leere Alarmliste",
    nothingToSee = "Hier gibt es nichts zu sehen",
    alarms = "Alarme",
    deleteAll = "Alle löschen",
    settings = "Einstellungen",
    toneUnavailable = "Ton nicht verfügbar",
    clear = "Klar",
    maximumSnoozes = "Maximale Schlummeranzahl",
    unlimitedSnoozes = "Unbegrenzt",
    noSnoozesLeft = "Kein Schlummern mehr möglich",
    snoozesLeft = { count -> "Noch $count Schlummerpausen" },
    snoozeLimitSummary = { count, minutes -> "$count Schlummerpausen · bis zu $minutes zusätzliche Minuten" },
    snoozeOff = "Aus",
    allowSnooze = "Schlummern erlauben",
    snoozeDuration = "Dauer (Minuten)",
    snoozeDurationHint = "Wähle 1–30 Minuten. Tippe zum Eingeben auf die Zahl.",
    applySnooze = "Einstellungen übernehmen",
    snoozeMaximumSummary = { count -> "Maximal $count" },
    snoozeSettingsSummary = { minutes, limit -> "$minutes Min. · $limit" },
    snooze = "Schlummern",
    enter = "Eintreten",
    noRingtonePicker = "Kein Klingeltonauswahl",
    alarmTitle = "Alarmtitel",
    goodDay = "Guten Tag",
    defaultAlarmTone = "Standard-Alarmton",
    disabledNotificationMessage = "Benachrichtigungen sind für diese App deaktiviert.",
    ok = "OK",
    notificationPermissionDialogMessage = "Diese App benötigt die Berechtigung zum Anzeigen von Benachrichtigungen.",
    repeatWeekly = "Wöchentlich wiederholen",
    vibrate = "Vibrieren",
    testAlarm = "Testalarm",
    save = "Sparen",
    easyMath = "Einfache Mathematik",
    mediumMath = "Mittlere Mathematik",
    hardMath = "Schwere Mathematik",
    selectHour = "Stunde auswählen",
    cancel = "Stornieren",
    input = "Eingang",
    picker = "Picker",
    system = "System",
    dark = "Dunkel",
    light = "Licht",
    appSettings = "App-Einstellungen",
    back = "Zurück",
    colorTheme = "Farbthema",
    alarmOrder = "Alarmreihenfolge",
    alarmOrderDescription = "Wahle, ob Alarme nach ihrer Erstellung oder nach ihrer Auslosezeit angezeigt werden.",
    creationOrder = "Erstellungsreihenfolge",
    timeOrder = "Zeit",
    help = "Hilfe",
    sendFeedback = "Feedback senden",
    sendFeedbackMessage = "Feedback an den Entwickler senden",
    supportEmail = "aregbestimi@gmail.com",
    emailChooserTitle = "E-Mail senden",
    shareMathAlarm = "Mathematik-Alarm teilen",
    shareWithOthers = "Dies ist eine coole Alarm-App",
    share = "Teilen",
    defaultSendText = "Standard-Alarm",
    disabledNotificationMessageExtended = "Benachrichtigungen dieser Anwendung sind deaktiviert. Bitte gehen Sie zu den Geräteeinstellungen und aktivieren Sie sie.",
    taskAlarmPermissionDialogText = "Damit Alarme funktionieren, benötigt Math Alarm die Berechtigung zum Einstellen von Alarmen. Wird diese Berechtigung nicht erteilt, funktionieren auch die vorhandenen Alarme nicht.",
    taskAlarmPermissionDialogConfirm = "Bestätigen",
    taskAlarmPermissionDialogCancel = "Nicht jetzt",
    notification = "Benachrichtigung",
    alert = "Klingelton",
    grantPermission = "Berechtigung erteilen",
    permissionsExternalStorageText = { tone ->
        "Es scheint, dass wir $tone nicht abspielen können, wahrscheinlich weil eine Erlaubnis erforderlich ist. Wenn Sie möchten, können Sie die Erlaubnis erteilen. Alternativ können Sie einen anderen Ton auswählen. Diese Entscheidung kann in den Systemeinstellungen geändert werden."
    }
)

private fun questionCountDe(count: Int): String =
    if (count == 1) "$count Aufgabe" else "$count Aufgaben"
