package com.timilehinaregbesola.mathalarm.utils.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.EN, default = true)
val EnMathAlarmStrings = Strings(
    selectAlarmPrompt = "Select an alarm or create a new one",
    closeAlarmEditor = "Close this editor?",
    closeAlarmEditorMessage = "Any unsaved changes to this alarm will be discarded.",
    discardChanges = "Discard changes",

    mathDifficultyNames = listOf("Easy", "Medium", "Hard", "Custom"),
    mathChallengeTitle = "Math challenge",
    mixedDifficulty = "Mixed difficulty",
    mixDifficulties = "Mix difficulties",
    mathDifficulty = "Difficulty",
    mathOperations = "Operations",
    addition = "Addition",
    subtraction = "Subtraction",
    multiplication = "Multiplication",
    division = "Division",
    additionAndSubtraction = "Addition & subtraction",
    multiplicationAndDivision = "Multiplication & division",
    mathExample = "Example",
    refreshExample = "Refresh",
    applyChallenge = "Apply challenge",
    easiestFirst = "Easiest first",
    questions = "Questions",
    chooseRange = "Choose range",
    checkAnswer = "Check answer",
    nextFeature = "Next",
    snoozeAnnouncementTitle = "Snooze on your terms",
    snoozeAnnouncementDescription = "Set a snooze limit, choose a duration from 1–30 minutes, or turn snooze off. New alarms start with 3 snoozes of 5 minutes. Existing alarms keep their snooze limits.",
    snoozeAnnouncementInstructions = "Use the Snooze checkbox for a quick on/off toggle. Tap Edit beside it to change the limit and duration.",
    whatsNew = "What’s new",
    latestFeatures = "Explore the latest features",
    gotIt = "Got it",
    tryFeature = "Try it",
    challengeAnnouncementTitle = "More ways to wake up",
    challengeAnnouncementInstructions = "Add or edit an alarm, then tap Edit next to Math challenge.",
    exampleChallenge = "Example challenge",
    exampleDifficultyMix = { easy, medium -> "Easy: $easy · Medium: $medium" },
    challengeAnnouncementDescription = { maximum -> "Solve up to $maximum questions. Mix difficulties or build a custom challenge that works for you." },
    questionCount = ::questionCountEn,
    challengeSummary = { difficulty, count -> "$difficulty · ${questionCountEn(count)}" },
    mixedQuestionTotal = { count, maximum -> "${questionCountEn(count)} total · Maximum $maximum" },
    questionProgress = { current, total -> "Question $current of $total" },
    questionCountHint = { maximum -> "Choose 1–$maximum. Tap the number to type." },
    difficultyQuestionLabel = { difficulty -> "Questions: $difficulty" },
    decreaseQuestionCount = { label -> "Decrease count: $label" },
    increaseQuestionCount = { label -> "Increase count: $label" },
    alarmScheduleFailed = "Couldn’t schedule alarm. Save it again.",
    alarmSaveFailed = "Couldn’t save alarm. Try again.",
    alarmUpdateFailed = "Couldn’t update alarm. Try again.",
    alarmDismissFailed = "Couldn’t dismiss alarm. Try again.",
    alarmSnoozeFailed = "Couldn’t snooze alarm. Try again.",
    incorrectAnswer = "Incorrect answer. Try again.",
    multipleDays = "Multiple Days",
    greeting = { hour ->
        when {
            hour < 12 -> "Good Morning"
            hour in 12..17 -> "Afternoon"
            else -> "Good Evening"
        }
    },
    expand = "Expand",
    delete = "Delete",
    edit = "Edit",
    dateLocale = "en",
    skipAnnouncementDescription = "Take a break from your next alarm without changing the rest of your schedule.",
    skipAnnouncementInstructions = "Expand an enabled alarm and tap Skip next. Available for weekly alarms and alarms with multiple selected days.",
    skipAnnouncementUndo = "Only the next occurrence is skipped; other selected days stay scheduled. That weekday returns the following week for repeating alarms. Non-repeating alarms keep only their remaining dates. Tap Undo before the skipped time to bring it back. Snoozes and other alarms stay scheduled.",
    viewAlarms = "View alarms",
    skipAnnouncementExample = "Try this example",
    skipNext = "Skip next",
    skippedAlarmOn = { date -> "Skipped · $date" },
    undo = "Undo",
    undoSkip = "Undo skip",
    collapse = "Collapse",
    noUpcomingAlarms = "No Upcoming Alarms",
    nextAlarmText = "Next alarm:",
    nextOccurrenceOn = { date -> "Next: $date" },
    nextAlarmIn = { hours, minutes ->
        if (hours == 0 && minutes == 0) "Next alarm in less than a minute"
        else "Next alarm in " + listOfNotNull(
            if (hours > 0) "$hours ${if (hours == 1) "hour" else "hours"}" else null,
            if (minutes > 0) "$minutes ${if (minutes == 1) "minute" else "minutes"}" else null,
        ).joinToString(" ")
    },
    alarmSet = "Alarm Set for",
    alarmPermissionDialogConfirm = "Confirm",
    alarmPermissionDialogCancel = "Cancel",
    alarmPermissionDialogText = "This app requires permission to set alarms.",
    alarmPermissionDialogTitle = "Permission Required",
    clearAlarmDialogConfirm = "Confirm",
    clearAlarmDialogCancel = "Cancel",
    clearAlarmDialogText = "Are you sure you want to clear the alarms?",
    clearAlarmDialogTitle = "Clear Alarms",
    emptyAlarmList = "Empty Alarm List",
    nothingToSee = "Nothing to see here",
    alarms = "Alarms",
    deleteAll = "Delete All",
    settings = "Settings",
    toneUnavailable = "Tone Unavailable",
    clear = "Clear",
    maximumSnoozes = "Maximum snoozes",
    unlimitedSnoozes = "Unlimited",
    noSnoozesLeft = "No snoozes left",
    snoozesLeft = { count -> if (count == 1) "1 snooze left" else "$count snoozes left" },
    snoozeLimitSummary = { count, minutes -> "$count ${if (count == 1) "snooze" else "snoozes"} · up to $minutes extra minutes" },
    snoozeOff = "Off",
    allowSnooze = "Allow snooze",
    snoozeDuration = "Duration (minutes)",
    snoozeDurationHint = "Choose 1–30 minutes. Tap the number to type.",
    applySnooze = "Apply snooze settings",
    snoozeMaximumSummary = { count -> "Maximum $count" },
    snoozeSettingsSummary = { minutes, limit -> "$minutes min · $limit" },
    snooze = "Snooze",
    enter = "Enter",
    noRingtonePicker = "No Ringtone Picker",
    alarmTitle = "Alarm Title",
    goodDay = "Good day",
    defaultAlarmTone = "Alarm Tone (Default)",
    disabledNotificationMessage = "Notifications are disabled for this app.",
    disabledNotificationMessageExtended = "Notifications of this application are disabled. Please go to your device settings and enable them.",
    ok = "OK",
    notificationPermissionDialogMessage = "This app requires permission to show notifications.",
    repeatWeekly = "Repeat Weekly",
    vibrate = "Vibrate",
    testAlarm = "Test Alarm",
    save = "Save",
    easyMath = "Easy Math",
    mediumMath = "Medium Math",
    hardMath = "Hard Math",
    selectHour = "Select Hour",
    cancel = "Cancel",
    input = "Input",
    picker = "Picker",
    system = "System",
    dark = "Dark",
    light = "Light",
    appSettings = "App Settings",
    back = "Back",
    colorTheme = "Color Theme",
    alarmOrder = "Alarm Order",
    alarmOrderDescription = "Choose whether alarms appear by when they were created or by the time they go off.",
    creationOrder = "Creation Order",
    timeOrder = "Time",
    help = "Help",
    sendFeedback = "Send Feedback",
    sendFeedbackMessage = "Send feedback to the developer",
    supportEmail = "aregbestimi@gmail.com",
    emailChooserTitle = "Send Email",
    defaultSendText = "Default Alarm",
    shareMathAlarm = "Share Math Alarm",
    shareWithOthers = "Check out this cool alarm app",
    share = "Share",
    taskAlarmPermissionDialogText = "In order for alarms to work, Math alarm needs the permission to set alarms. If this permission is not granted, the existing alarms will not work as well.",
    taskAlarmPermissionDialogCancel = "Not now",
    taskAlarmPermissionDialogConfirm = "Grant",
    notification = "Notification",
    alert = "Ringtone",
    grantPermission = "Grant Permission",
    permissionsExternalStorageText = { tone ->
        "It seems that we cannot play $tone, probably because a permission is required. If you want, you can grant the permission. Alternatively, select a different sound. This decision can be changed in System Settings."
    }
)

private fun questionCountEn(count: Int): String =
    if (count == 1) "$count question" else "$count questions"
