package com.timilehinaregbesola.mathalarm.utils.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.ES)
val EsMathAlarmStrings = Strings(
    mathDifficultyNames = listOf("Fácil", "Media", "Difícil", "Personalizada"),
    mathChallengeTitle = "Reto matemático",
    mixedDifficulty = "Dificultad mixta",
    mixDifficulties = "Combinar dificultades",
    mathDifficulty = "Dificultad",
    mathOperations = "Operaciones",
    addition = "Suma",
    subtraction = "Resta",
    multiplication = "Multiplicación",
    division = "División",
    additionAndSubtraction = "Suma y resta",
    multiplicationAndDivision = "Multiplicación y división",
    mathExample = "Ejemplo",
    refreshExample = "Actualizar",
    applyChallenge = "Aplicar reto",
    easiestFirst = "Más fáciles primero",
    questions = "Preguntas",
    chooseRange = "Elegir rango",
    checkAnswer = "Comprobar respuesta",
    whatsNew = "Novedades",
    latestFeatures = "Descubre las últimas funciones",
    gotIt = "Entendido",
    tryFeature = "Probar",
    challengeAnnouncementTitle = "Más formas de despertarte",
    challengeAnnouncementInstructions = "Añade o edita una alarma y toca Editar junto a Reto matemático.",
    exampleChallenge = "Reto de ejemplo",
    questionCount = ::questionCountEs,
    challengeSummary = { difficulty, count -> "$difficulty · ${questionCountEs(count)}" },
    mixedQuestionTotal = { count, maximum -> "${questionCountEs(count)} en total · Máximo: $maximum" },
    questionProgress = { current, total -> "Pregunta $current de $total" },
    questionCountHint = { maximum -> "Elige entre 1 y $maximum. Toca el número para escribir." },
    difficultyQuestionLabel = { difficulty -> "Preguntas: $difficulty" },
    decreaseQuestionCount = { label -> "Reducir cantidad: $label" },
    increaseQuestionCount = { label -> "Aumentar cantidad: $label" },
    exampleDifficultyMix = { easy, medium -> "Fácil: $easy · Media: $medium" },
    challengeAnnouncementDescription = { maximum -> "Resuelve hasta $maximum preguntas. Combina dificultades o crea un reto a tu medida." },
    alarmScheduleFailed = "No se pudo programar la alarma. Guárdala de nuevo.",
    alarmSaveFailed = "No se pudo guardar la alarma. Inténtalo de nuevo.",
    alarmUpdateFailed = "No se pudo actualizar la alarma. Inténtalo de nuevo.",
    alarmDismissFailed = "No se pudo detener la alarma. Inténtalo de nuevo.",
    alarmSnoozeFailed = "No se pudo posponer la alarma. Inténtalo de nuevo.",
    incorrectAnswer = "Respuesta incorrecta. Inténtalo de nuevo.",
    multipleDays = "Días múltiples",
    greeting = { hour ->
        when {
            hour < 12 -> "Buenos días"
            hour in 12..17 -> "Buenas tardes"
            else -> "Buenas noches"
        }
    },
    expand = "Expandir",
    delete = "Eliminar",
    edit = "Editar",
    skipNext = "Omitir próxima alarma",
    undoSkip = "Deshacer omisión",
    collapse = "Colapsar",
    noUpcomingAlarms = "No hay alarmas próximas",
    nextAlarmText = "Próxima alarma en",
    alarmSet = "Alarma establecida para",
    alarmPermissionDialogConfirm = "Confirmar",
    alarmPermissionDialogCancel = "Cancelar",
    alarmPermissionDialogText = "Esta aplicación requiere permiso para establecer alarmas.",
    alarmPermissionDialogTitle = "Permiso requerido",
    clearAlarmDialogConfirm = "Confirmar",
    clearAlarmDialogCancel = "Cancelar",
    clearAlarmDialogText = "¿Estás seguro de que quieres borrar esta alarmas?",
    clearAlarmDialogTitle = "Borrar alarma",
    emptyAlarmList = "Lista de alarmas vacía",
    nothingToSee = "Nada que ver aquí",
    alarms = "Alarmas",
    deleteAll = "Eliminar todo",
    settings = "Ajustes",
    toneUnavailable = "Tono no disponible",
    clear = "Borrar",
    snooze = "Siesta",
    enter = "Entrar",
    noRingtonePicker = "Selector de tonos no disponible",
    alarmTitle = "Título de la alarma",
    goodDay = "Buen día",
    defaultAlarmTone = "Tono de alarma (predeterminado)",
    disabledNotificationMessage = "Las notificaciones están desactivadas para esta aplicación.",
    disabledNotificationMessageExtended = "Las notificaciones de esta aplicación están desactivadas. Por favor, vaya a la configuración de su dispositivo y actívelas.",
    ok = "OK",
    notificationPermissionDialogMessage = "Esta aplicación requiere permiso para mostrar notificaciones.",
    repeatWeekly = "Repetir semanalmente",
    vibrate = "Vibrar",
    testAlarm = "Probar alarma",
    save = "Guardar",
    easyMath = "Matemáticas fáciles",
    mediumMath = "Matemáticas medias",
    hardMath = "Matemáticas difíciles",
    selectHour = "Seleccionar hora",
    cancel = "Cancelar",
    input = "Entrada",
    picker = "Selector",
    system = "Sistema",
    dark = "Oscuro",
    light = "Claro",
    appSettings = "Ajustes de la aplicación",
    back = "Atrás",
    colorTheme = "Tema de color",
    alarmOrder = "Orden de alarmas",
    alarmOrderDescription = "Elige si las alarmas aparecen por orden de creacion o por la hora en que suenan.",
    creationOrder = "Orden de creación",
    timeOrder = "Hora",
    alert = "Alerta",
    help = "Ayuda",
    sendFeedback = "Enviar comentarios",
    defaultSendText = "Alarma predeterminada",
    supportEmail = "aregbestimi@gmail.com",
    emailChooserTitle = "Enviar correo electrónico",
    sendFeedbackMessage = "Envía comentarios al desarrollador",
    shareMathAlarm = "Compartir Math Alarm",
    shareWithOthers = "Echa un vistazo a esta genial aplicación de alarma",
    grantPermission = "Permitir",
    notification = "Notificación",
    permissionsExternalStorageText = { tone ->
        "Parece que no podemos reproducir $tone, probablemente porque se requiere permiso. Si lo deseas, puedes otorgar el permiso. Alternativamente, seleccione un sonido diferente. Esta decisión se puede cambiar en Configuración del sistema."
    },
    share = "Compartir",
    taskAlarmPermissionDialogText = "Para que las alarmas funcionen, Math Alarm necesita el permiso para establecer alarmas. Si no se concede este permiso, las alarmas existentes tampoco funcionarán.",
    taskAlarmPermissionDialogCancel = "Ahora no",
    taskAlarmPermissionDialogConfirm = "Conceder"
)

private fun questionCountEs(count: Int): String =
    if (count == 1) "$count pregunta" else "$count preguntas"
