package com.timilehinaregbesola.mathalarm.utils.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.HI)
val HiMathAlarmStrings = Strings(
    mathDifficultyNames = listOf("आसान", "मध्यम", "कठिन", "कस्टम"),
    mathChallengeTitle = "गणित चुनौती",
    mixedDifficulty = "मिली-जुली कठिनाई",
    mixDifficulties = "कठिनाई स्तर मिलाएँ",
    mathDifficulty = "कठिनाई",
    mathOperations = "संक्रियाएँ",
    addition = "जोड़",
    subtraction = "घटाव",
    multiplication = "गुणा",
    division = "भाग",
    additionAndSubtraction = "जोड़ और घटाव",
    multiplicationAndDivision = "गुणा और भाग",
    mathExample = "उदाहरण",
    refreshExample = "नया उदाहरण",
    applyChallenge = "चुनौती लागू करें",
    easiestFirst = "पहले आसान सवाल",
    questions = "सवाल",
    chooseRange = "सीमा चुनें",
    checkAnswer = "उत्तर जाँचें",
    nextFeature = "अगला",
    snoozeAnnouncementTitle = "स्नूज़ आपके हिसाब से",
    snoozeAnnouncementDescription = "स्नूज़ की सीमा तय करें, 1–30 मिनट का समय चुनें या स्नूज़ बंद करें। नए अलार्म में 5 मिनट के 3 स्नूज़ मिलते हैं। मौजूदा अलार्म की स्नूज़ सीमा बनी रहती है।",
    snoozeAnnouncementInstructions = "स्नूज़ चेकबॉक्स से तुरंत चालू या बंद करें। सीमा और समय बदलने के लिए उसके पास संपादित करें पर टैप करें।",
    whatsNew = "नया क्या है",
    latestFeatures = "नई सुविधाएँ देखें",
    gotIt = "समझ गया",
    tryFeature = "आज़माएँ",
    challengeAnnouncementTitle = "जागने के और तरीके",
    challengeAnnouncementInstructions = "अलार्म जोड़ें या बदलें, फिर गणित चुनौती के पास संपादित करें पर टैप करें।",
    exampleChallenge = "चुनौती का उदाहरण",
    exampleDifficultyMix = { easy, medium -> "आसान: $easy · मध्यम: $medium" },
    challengeAnnouncementDescription = { maximum -> "अधिकतम $maximum सवाल हल करें। कठिनाई स्तर मिलाएँ या अपनी पसंद की चुनौती बनाएँ।" },
    questionCount = ::questionCountHi,
    challengeSummary = { difficulty, count -> "$difficulty · ${questionCountHi(count)}" },
    mixedQuestionTotal = { count, maximum -> "कुल ${questionCountHi(count)} · अधिकतम $maximum" },
    questionProgress = { current, total -> "$total में से सवाल $current" },
    questionCountHint = { maximum -> "1–$maximum चुनें। लिखने के लिए संख्या पर टैप करें।" },
    difficultyQuestionLabel = { difficulty -> "सवाल: $difficulty" },
    decreaseQuestionCount = { label -> "संख्या घटाएँ: $label" },
    increaseQuestionCount = { label -> "संख्या बढ़ाएँ: $label" },
    alarmScheduleFailed = "अलार्म सेट नहीं हुआ। फिर से सेव करें।",
    alarmSaveFailed = "अलार्म सेव नहीं हुआ। फिर कोशिश करें।",
    alarmUpdateFailed = "अलार्म अपडेट नहीं हुआ। फिर कोशिश करें।",
    alarmDismissFailed = "अलार्म बंद नहीं हुआ। फिर कोशिश करें।",
    alarmSnoozeFailed = "अलार्म स्नूज़ नहीं हुआ। फिर कोशिश करें।",
    incorrectAnswer = "गलत जवाब। फिर कोशिश करें।",
    multipleDays = "कई दिन",
    greeting = { hour ->
        when {
            hour < 12 -> "सुप्रभात"
            hour in 12..17 -> "शुभ अपराह्न"
            else -> "शुभ संध्या"
        }
    },
    expand = "विस्तार",
    delete = "हटाएं",
    edit = "संपादित करें",
    dateLocale = "hi",
    skipAnnouncementDescription = "बाकी समय-सारणी बदले बिना अगला अलार्म छोड़ें।",
    skipAnnouncementInstructions = "चालू अलार्म को खोलें और अगला छोड़ें पर टैप करें। यह साप्ताहिक अलार्म और कई चुने हुए दिनों वाले अलार्म के लिए उपलब्ध है।",
    skipAnnouncementUndo = "केवल अगली बार का अलार्म छोड़ा जाता है। साप्ताहिक अलार्म अगले सप्ताह फिर बजेंगे; बिना दोहराव वाले अलार्म की बाकी तारीखें बनी रहेंगी। छोड़े गए समय से पहले पूर्ववत करें पर टैप करके उसे वापस लाएँ। स्नूज़ और अन्य अलार्म तय समय पर बजेंगे।",
    viewAlarms = "अलार्म देखें",
    skipAnnouncementExample = "यह उदाहरण आज़माएँ",
    skipNext = "अगला छोड़ें",
    skippedAlarmOn = { date -> "छोड़ा गया · $date" },
    undo = "पूर्ववत करें",
    undoSkip = "छोड़ना पूर्ववत करें",
    collapse = "संक्षेप करें",
    noUpcomingAlarms = "कोई आगामी अलार्म नहीं",
    nextAlarmText = "अगला अलार्म:",
    nextOccurrenceOn = { date -> "अगला: $date" },
    nextAlarmIn = { hours, minutes ->
        if (hours == 0 && minutes == 0) "अगला अलार्म एक मिनट से कम समय में"
        else "अगला अलार्म " + listOfNotNull(
            if (hours > 0) "$hours घंटे" else null,
            if (minutes > 0) "$minutes मिनट" else null,
        ).joinToString(" ") + " में"
    },
    alarmSet = "अलार्म सेट किया गया",
    alarmPermissionDialogConfirm = "पुष्टि करें",
    alarmPermissionDialogCancel = "रद्द करें",
    alarmPermissionDialogText = "इस ऐप को अलार्म सेट करने की अनुमति की आवश्यकता है।",
    alarmPermissionDialogTitle = "अनुमति आवश्यक",
    clearAlarmDialogConfirm = "पुष्टि करें",
    clearAlarmDialogCancel = "रद्द करें",
    clearAlarmDialogText = "क्या आप वाकई अलार्म साफ़ करना चाहते हैं?",
    clearAlarmDialogTitle = "अलार्म साफ़ करें",
    emptyAlarmList = "खाली अलार्म सूची",
    nothingToSee = "यहाँ कुछ नहीं है",
    alarms = "अलार्म",
    deleteAll = "सभी हटाएं",
    settings = "सेटिंग्स",
    toneUnavailable = "स्वर अनुपलब्ध",
    clear = "साफ़ करें",
    maximumSnoozes = "अधिकतम स्नूज़",
    unlimitedSnoozes = "असीमित",
    noSnoozesLeft = "कोई स्नूज़ बाकी नहीं",
    snoozesLeft = { count -> "$count स्नूज़ बाकी हैं" },
    snoozeLimitSummary = { count, minutes -> "$count स्नूज़ · $minutes अतिरिक्त मिनट तक" },
    snoozeOff = "बंद",
    allowSnooze = "स्नूज़ की अनुमति दें",
    snoozeDuration = "अवधि (मिनट)",
    snoozeDurationHint = "1–30 मिनट चुनें। टाइप करने के लिए संख्या पर टैप करें।",
    applySnooze = "स्नूज़ सेटिंग लागू करें",
    snoozeMaximumSummary = { count -> "अधिकतम $count" },
    snoozeSettingsSummary = { minutes, limit -> "$minutes मिनट · $limit" },
    snooze = "स्नूज़",
    enter = "प्रवेश करें",
    noRingtonePicker = "कोई रिंगटोन पिकर नहीं",
    alarmTitle = "अलार्म शीर्षक",
    goodDay = "शुभ दिन",
    defaultAlarmTone = "अलार्म स्वर (डिफ़ॉल्ट)",
    disabledNotificationMessage = "इस ऐप के लिए सूचनाएँ अक्षम हैं।",
    disabledNotificationMessageExtended = "इस एप्लिकेशन की सूचनाएँ अक्षम हैं। कृपया अपने डिवाइस सेटिंग्स में जाएं और उन्हें सक्षम करें।",
    ok = "ठीक है",
    notificationPermissionDialogMessage = "इस ऐप को सूचनाएं दिखाने की अनुमति की आवश्यकता है।",
    repeatWeekly = "साप्ताहिक दोहराएं",
    vibrate = "कंपन",
    testAlarm = "परीक्षण अलार्म",
    save = "सहेजें",
    easyMath = "आसान गणित",
    mediumMath = "मध्यम गणित",
    hardMath = "कठिन गणित",
    selectHour = "घंटा चुनें",
    cancel = "रद्द करें",
    input = "इनपुट",
    picker = "पिकर",
    system = "सिस्टम",
    dark = "डार्क",
    light = "लाइट",
    appSettings = "ऐप सेटिंग्स",
    back = "वापस",
    colorTheme = "रंग थीम",
    alarmOrder = "अलार्म क्रम",
    alarmOrderDescription = "चुनें कि अलार्म उनके बनाए जाने के क्रम में दिखें या बजने के समय के अनुसार।",
    creationOrder = "बनाने का क्रम",
    timeOrder = "समय",
    help = "मदद",
    sendFeedback = "प्रतिक्रिया भेजें",
    sendFeedbackMessage = "डेवलपर को प्रतिक्रिया भेजें",
    supportEmail = "aregbestimi@gmail.com",
    emailChooserTitle = "ईमेल भेजें",
    defaultSendText = "डिफ़ॉल्ट अलार्म",
    shareMathAlarm = "मैथ अलार्म साझा करें",
    shareWithOthers = "इस शानदार अलार्म ऐप को देखें",
    share = "साझा करें",
    taskAlarmPermissionDialogText = "अलार्म काम करने के लिए, मैथ अलार्म को अलार्म सेट करने की अनुमति की आवश्यकता है। यदि यह अनुमति नहीं दी गई है, तो मौजूदा अलार्म भी काम नहीं करेंगे।",
    taskAlarmPermissionDialogCancel = "अभी नहीं",
    taskAlarmPermissionDialogConfirm = "अनुमति दें",
    notification = "सूचना",
    alert = "रिंगटोन",
    grantPermission = "अनुमति दें",
    permissionsExternalStorageText = { tone ->
        "ऐसा लगता है कि हम $tone नहीं चला सकते, शायद क्योंकि अनुमति की आवश्यकता है। यदि आप चाहें तो अनुमति दे सकते हैं। वैकल्पिक रूप से, एक अलग ध्वनि चुनें। यह निर्णय सिस्टम सेटिंग्स में बदला जा सकता है।"
    }
)

private fun questionCountHi(count: Int): String =
    "$count सवाल"
