package com.timilehinaregbesola.mathalarm.utils.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.PA)
val PaMathAlarmStrings = Strings(
    selectAlarmPrompt = "ਅਲਾਰਮ ਚੁਣੋ ਜਾਂ ਨਵਾਂ ਬਣਾਓ",
    closeAlarmEditor = "ਸੰਪਾਦਕ ਬੰਦ ਕਰਨਾ ਹੈ?",
    closeAlarmEditorMessage = "ਇਸ ਅਲਾਰਮ ਦੀਆਂ ਅਣਰੱਖਿਅਤ ਤਬਦੀਲੀਆਂ ਮਿਟਾ ਦਿੱਤੀਆਂ ਜਾਣਗੀਆਂ।",
    discardChanges = "ਤਬਦੀਲੀਆਂ ਮਿਟਾਓ",

    mathDifficultyNames = listOf("ਸੌਖਾ", "ਦਰਮਿਆਨਾ", "ਔਖਾ", "ਕਸਟਮ"),
    mathChallengeTitle = "ਗਣਿਤ ਚੁਣੌਤੀ",
    mixedDifficulty = "ਮਿਲੀ-ਜੁਲੀ ਮੁਸ਼ਕਲ",
    mixDifficulties = "ਮੁਸ਼ਕਲ ਦੇ ਪੱਧਰ ਮਿਲਾਓ",
    mathDifficulty = "ਮੁਸ਼ਕਲ",
    mathOperations = "ਗਣਿਤ ਕਿਰਿਆਵਾਂ",
    addition = "ਜੋੜ",
    subtraction = "ਘਟਾਓ",
    multiplication = "ਗੁਣਾ",
    division = "ਭਾਗ",
    additionAndSubtraction = "ਜੋੜ ਅਤੇ ਘਟਾਓ",
    multiplicationAndDivision = "ਗੁਣਾ ਅਤੇ ਭਾਗ",
    mathExample = "ਉਦਾਹਰਨ",
    refreshExample = "ਨਵੀਂ ਉਦਾਹਰਨ",
    applyChallenge = "ਚੁਣੌਤੀ ਲਾਗੂ ਕਰੋ",
    easiestFirst = "ਪਹਿਲਾਂ ਸੌਖੇ ਸਵਾਲ",
    questions = "ਸਵਾਲ",
    chooseRange = "ਸੀਮਾ ਚੁਣੋ",
    checkAnswer = "ਜਵਾਬ ਜਾਂਚੋ",
    nextFeature = "ਅੱਗੇ",
    snoozeAnnouncementTitle = "ਤੁਹਾਡੀ ਪਸੰਦ ਅਨੁਸਾਰ ਸਨੂਜ਼",
    snoozeAnnouncementDescription = "ਸਨੂਜ਼ ਦੀ ਸੀਮਾ ਤੈਅ ਕਰੋ, 1–30 ਮਿੰਟ ਦਾ ਸਮਾਂ ਚੁਣੋ ਜਾਂ ਸਨੂਜ਼ ਬੰਦ ਕਰੋ। ਨਵੇਂ ਅਲਾਰਮਾਂ ਵਿੱਚ 5 ਮਿੰਟ ਦੇ 3 ਸਨੂਜ਼ ਹੁੰਦੇ ਹਨ। ਮੌਜੂਦਾ ਅਲਾਰਮਾਂ ਦੀ ਸਨੂਜ਼ ਸੀਮਾ ਬਰਕਰਾਰ ਰਹਿੰਦੀ ਹੈ।",
    snoozeAnnouncementInstructions = "ਸਨੂਜ਼ ਚੈੱਕਬਾਕਸ ਨਾਲ ਛੇਤੀ ਚਾਲੂ ਜਾਂ ਬੰਦ ਕਰੋ। ਸੀਮਾ ਅਤੇ ਸਮਾਂ ਬਦਲਣ ਲਈ ਇਸਦੇ ਨਾਲ ਸੰਪਾਦਿਤ ਕਰੋ ਉੱਤੇ ਟੈਪ ਕਰੋ।",
    whatsNew = "ਨਵਾਂ ਕੀ ਹੈ",
    latestFeatures = "ਨਵੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਦੇਖੋ",
    gotIt = "ਸਮਝ ਆ ਗਿਆ",
    tryFeature = "ਅਜ਼ਮਾਓ",
    challengeAnnouncementTitle = "ਜਾਗਣ ਦੇ ਹੋਰ ਤਰੀਕੇ",
    challengeAnnouncementInstructions = "ਅਲਾਰਮ ਜੋੜੋ ਜਾਂ ਬਦਲੋ, ਫਿਰ ਗਣਿਤ ਚੁਣੌਤੀ ਦੇ ਕੋਲ ਸੋਧੋ ਉੱਤੇ ਟੈਪ ਕਰੋ।",
    exampleChallenge = "ਚੁਣੌਤੀ ਦੀ ਉਦਾਹਰਨ",
    exampleDifficultyMix = { easy, medium -> "ਸੌਖੇ: $easy · ਦਰਮਿਆਨੇ: $medium" },
    challengeAnnouncementDescription = { maximum -> "ਵੱਧ ਤੋਂ ਵੱਧ $maximum ਸਵਾਲ ਹੱਲ ਕਰੋ। ਮੁਸ਼ਕਲ ਦੇ ਪੱਧਰ ਮਿਲਾਓ ਜਾਂ ਆਪਣੀ ਚੁਣੌਤੀ ਬਣਾਓ।" },
    questionCount = ::questionCountPa,
    challengeSummary = { difficulty, count -> "$difficulty · ${questionCountPa(count)}" },
    mixedQuestionTotal = { count, maximum -> "ਕੁੱਲ ${questionCountPa(count)} · ਵੱਧ ਤੋਂ ਵੱਧ $maximum" },
    questionProgress = { current, total -> "$total ਵਿੱਚੋਂ ਸਵਾਲ $current" },
    questionCountHint = { maximum -> "1–$maximum ਚੁਣੋ। ਲਿਖਣ ਲਈ ਗਿਣਤੀ ਉੱਤੇ ਟੈਪ ਕਰੋ।" },
    difficultyQuestionLabel = { difficulty -> "ਸਵਾਲ: $difficulty" },
    decreaseQuestionCount = { label -> "ਗਿਣਤੀ ਘਟਾਓ: $label" },
    increaseQuestionCount = { label -> "ਗਿਣਤੀ ਵਧਾਓ: $label" },
    alarmScheduleFailed = "ਅਲਾਰਮ ਸੈੱਟ ਨਹੀਂ ਹੋਇਆ। ਦੁਬਾਰਾ ਸੇਵ ਕਰੋ।",
    alarmSaveFailed = "ਅਲਾਰਮ ਸੇਵ ਨਹੀਂ ਹੋਇਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    alarmUpdateFailed = "ਅਲਾਰਮ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋਇਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    alarmDismissFailed = "ਅਲਾਰਮ ਬੰਦ ਨਹੀਂ ਹੋਇਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    alarmSnoozeFailed = "ਅਲਾਰਮ ਸਨੂਜ਼ ਨਹੀਂ ਹੋਇਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    incorrectAnswer = "ਗਲਤ ਜਵਾਬ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    multipleDays = "ਕਈ ਦਿਨ",
    greeting = { hour ->
        when {
            hour < 12 -> "ਸ਼ੁਭ ਸਵੇਰ"
            hour in 12..17 -> "ਦੁਪਹਿਰ"
            else -> "ਸ਼ੁਭ ਸ਼ਾਮ"
        }
    },
    expand = "ਵਿਸਤਾਰ",
    delete = "ਹਟਾਓ",
    edit = "ਸੋਧੋ",
    dateLocale = "pa",
    skipAnnouncementDescription = "ਬਾਕੀ ਸਮਾਂ-ਸਾਰਣੀ ਬਦਲੇ ਬਿਨਾਂ ਅਗਲਾ ਅਲਾਰਮ ਛੱਡੋ।",
    skipAnnouncementInstructions = "ਚਾਲੂ ਅਲਾਰਮ ਨੂੰ ਫੈਲਾਓ ਅਤੇ ਅਗਲਾ ਛੱਡੋ ਉੱਤੇ ਟੈਪ ਕਰੋ। ਇਹ ਹਫ਼ਤਾਵਾਰੀ ਅਲਾਰਮਾਂ ਅਤੇ ਕਈ ਚੁਣੇ ਦਿਨਾਂ ਵਾਲੇ ਅਲਾਰਮਾਂ ਲਈ ਉਪਲਬਧ ਹੈ।",
    skipAnnouncementUndo = "ਸਿਰਫ਼ ਅਗਲੀ ਵਾਰ ਦਾ ਅਲਾਰਮ ਛੱਡਿਆ ਜਾਂਦਾ ਹੈ। ਹਫ਼ਤਾਵਾਰੀ ਅਲਾਰਮ ਅਗਲੇ ਹਫ਼ਤੇ ਮੁੜ ਵੱਜਣਗੇ; ਬਿਨਾਂ ਦੁਹਰਾਓ ਵਾਲੇ ਅਲਾਰਮਾਂ ਦੀਆਂ ਬਾਕੀ ਤਾਰੀਖਾਂ ਰਹਿਣਗੀਆਂ। ਛੱਡੇ ਸਮੇਂ ਤੋਂ ਪਹਿਲਾਂ ਵਾਪਸ ਲਓ ਉੱਤੇ ਟੈਪ ਕਰਕੇ ਇਸਨੂੰ ਮੁੜ ਲਿਆਓ। ਸਨੂਜ਼ ਅਤੇ ਹੋਰ ਅਲਾਰਮ ਤੈਅ ਸਮੇਂ ਉੱਤੇ ਵੱਜਣਗੇ।",
    viewAlarms = "ਅਲਾਰਮ ਵੇਖੋ",
    skipAnnouncementExample = "ਇਹ ਉਦਾਹਰਨ ਅਜ਼ਮਾਓ",
    skipNext = "ਅਗਲਾ ਛੱਡੋ",
    skippedAlarmOn = { date -> "ਛੱਡਿਆ · $date" },
    undo = "ਵਾਪਸ ਲਓ",
    undoSkip = "ਛੱਡਣਾ ਵਾਪਸ ਲਓ",
    collapse = "ਸੰਕੁਚਿਤ",
    noUpcomingAlarms = "ਕੋਈ ਆਉਣ ਵਾਲੇ ਅਲਾਰਮ ਨਹੀਂ",
    nextAlarmText = "ਅਗਲਾ ਅਲਾਰਮ:",
    nextOccurrenceOn = { date -> "ਅਗਲਾ: $date" },
    nextAlarmIn = { hours, minutes ->
        if (hours == 0 && minutes == 0) "ਅਗਲਾ ਅਲਾਰਮ ਇੱਕ ਮਿੰਟ ਤੋਂ ਘੱਟ ਸਮੇਂ ਵਿੱਚ"
        else "ਅਗਲਾ ਅਲਾਰਮ " + listOfNotNull(
            if (hours > 0) "$hours ${if (hours == 1) "ਘੰਟੇ" else "ਘੰਟਿਆਂ"}" else null,
            if (minutes > 0) "$minutes ਮਿੰਟ" else null,
        ).joinToString(" ") + " ਵਿੱਚ"
    },
    alarmSet = "ਅਲਾਰਮ ਸੈੱਟ ਕੀਤਾ ਗਿਆ",
    alarmPermissionDialogConfirm = "ਪੁਸ਼ਟੀ ਕਰੋ",
    alarmPermissionDialogCancel = "ਰੱਦ ਕਰੋ",
    alarmPermissionDialogText = "ਇਸ ਐਪ ਨੂੰ ਅਲਾਰਮ ਸੈੱਟ ਕਰਨ ਦੀ ਆਗਿਆ ਦੀ ਲੋੜ ਹੈ।",
    alarmPermissionDialogTitle = "ਆਗਿਆ ਲੋੜੀਂਦੀ ਹੈ",
    clearAlarmDialogConfirm = "ਪੁਸ਼ਟੀ ਕਰੋ",
    clearAlarmDialogCancel = "ਰੱਦ ਕਰੋ",
    clearAlarmDialogText = "ਕੀ ਤੁਸੀਂ ਇਹ ਅਲਾਰਮ ਸਾਫ਼ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    clearAlarmDialogTitle = "ਅਲਾਰਮ ਸਾਫ਼ ਕਰੋ",
    emptyAlarmList = "ਖਾਲੀ ਅਲਾਰਮ ਸੂਚੀ",
    nothingToSee = "ਇਥੇ ਕੁਝ ਨਹੀਂ",
    alarms = "ਅਲਾਰਮ",
    deleteAll = "ਸਭ ਨੂੰ ਹਟਾਓ",
    settings = "ਸੈਟਿੰਗਜ਼",
    toneUnavailable = "ਟੋਨ ਉਪਲਬਧ ਨਹੀਂ",
    clear = "ਸਾਫ਼ ਕਰੋ",
    maximumSnoozes = "ਵੱਧ ਤੋਂ ਵੱਧ ਸਨੂਜ਼",
    unlimitedSnoozes = "ਅਸੀਮਤ",
    noSnoozesLeft = "ਕੋਈ ਸਨੂਜ਼ ਬਾਕੀ ਨਹੀਂ",
    snoozesLeft = { count -> "$count ਸਨੂਜ਼ ਬਾਕੀ ਹਨ" },
    snoozeLimitSummary = { count, minutes -> "$count ਸਨੂਜ਼ · $minutes ਵਾਧੂ ਮਿੰਟ ਤੱਕ" },
    snoozeOff = "ਬੰਦ",
    allowSnooze = "ਸਨੂਜ਼ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ",
    snoozeDuration = "ਮਿਆਦ (ਮਿੰਟ)",
    snoozeDurationHint = "1–30 ਮਿੰਟ ਚੁਣੋ। ਟਾਈਪ ਕਰਨ ਲਈ ਨੰਬਰ ਉੱਤੇ ਟੈਪ ਕਰੋ।",
    applySnooze = "ਸਨੂਜ਼ ਸੈਟਿੰਗਾਂ ਲਾਗੂ ਕਰੋ",
    snoozeMaximumSummary = { count -> "ਵੱਧ ਤੋਂ ਵੱਧ $count" },
    snoozeSettingsSummary = { minutes, limit -> "$minutes ਮਿੰਟ · $limit" },
    snooze = "ਸਨੂਜ਼",
    enter = "ਦਾਖਲ ਕਰੋ",
    noRingtonePicker = "ਕੋਈ ਰਿੰਗਟੋਨ ਚੁਣਨ ਵਾਲਾ ਨਹੀਂ",
    alarmTitle = "ਅਲਾਰਮ ਸਿਰਲੇਖ",
    goodDay = "ਸ਼ੁਭ ਦਿਨ",
    defaultAlarmTone = "ਅਲਾਰਮ ਟੋਨ (ਡਿਫਾਲਟ)",
    disabledNotificationMessage = "ਇਸ ਐਪ ਲਈ ਨੋਟੀਫਿਕੇਸ਼ਨ ਅਸਮਰੱਥ ਹਨ।",
    disabledNotificationMessageExtended = "ਇਸ ਐਪਲੀਕੇਸ਼ਨ ਦੀਆਂ ਨੋਟੀਫਿਕੇਸ਼ਨ ਅਸਮਰੱਥ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਡਿਵਾਈਸ ਸੈਟਿੰਗਜ਼ ਵਿੱਚ ਜਾਓ ਅਤੇ ਉਹਨਾਂ ਨੂੰ ਸਮਰੱਥ ਕਰੋ।",
    ok = "ਠੀਕ ਹੈ",
    notificationPermissionDialogMessage = "ਇਸ ਐਪ ਨੂੰ ਨੋਟੀਫਿਕੇਸ਼ਨ ਦਿਖਾਉਣ ਦੀ ਆਗਿਆ ਦੀ ਲੋੜ ਹੈ।",
    repeatWeekly = "ਹਫਤਾਵਾਰੀ ਦੁਹਰਾਓ",
    vibrate = "ਵਾਈਬ੍ਰੇਟ",
    testAlarm = "ਪਰੀਖਣ ਅਲਾਰਮ",
    save = "ਸੰਭਾਲੋ",
    easyMath = "ਸੌਖੀ ਗਣਿਤ",
    mediumMath = "ਦਰਮਿਆਨੀ ਗਣਿਤ",
    hardMath = "ਕਠਿਨ ਗਣਿਤ",
    selectHour = "ਘੰਟਾ ਚੁਣੋ",
    cancel = "ਰੱਦ ਕਰੋ",
    input = "ਇਨਪੁੱਟ",
    picker = "ਚੁਣਨ ਵਾਲਾ",
    system = "ਸਿਸਟਮ",
    dark = "ਡਾਰਕ",
    light = "ਲਾਈਟ",
    appSettings = "ਐਪ ਸੈਟਿੰਗਜ਼",
    back = "ਪਿੱਛੇ",
    colorTheme = "ਰੰਗ ਥੀਮ",
    alarmOrder = "ਅਲਾਰਮ ਕ੍ਰਮ",
    alarmOrderDescription = "ਚੁਣੋ ਕਿ ਅਲਾਰਮ ਬਣਾਉਣ ਦੇ ਕ੍ਰਮ ਅਨੁਸਾਰ ਦਿਖਾਏ ਜਾਣ ਜਾਂ ਵੱਜਣ ਦੇ ਸਮੇਂ ਅਨੁਸਾਰ।",
    creationOrder = "ਬਣਾਉਣ ਦਾ ਕ੍ਰਮ",
    timeOrder = "ਸਮਾਂ",
    help = "ਮਦਦ",
    sendFeedback = "ਪ੍ਰਤੀਕ੍ਰਿਆ ਭੇਜੋ",
    sendFeedbackMessage = "ਡਿਵੈਲਪਰ ਨੂੰ ਪ੍ਰਤੀਕ੍ਰਿਆ ਭੇਜੋ",
    supportEmail = "aregbestimi@gmail.com",
    emailChooserTitle = "ਈਮੇਲ ਭੇਜੋ",
    defaultSendText = "ਡਿਫਾਲਟ ਅਲਾਰਮ",
    shareMathAlarm = "ਗਣਿਤ ਅਲਾਰਮ ਸਾਂਝਾ ਕਰੋ",
    shareWithOthers = "ਇਸ ਸ਼ਾਨਦਾਰ ਅਲਾਰਮ ਐਪ ਨੂੰ ਵੇਖੋ",
    share = "ਸਾਂਝਾ ਕਰੋ",
    taskAlarmPermissionDialogText = "ਅਲਾਰਮ ਕੰਮ ਕਰਨ ਲਈ, ਗਣਿਤ ਅਲਾਰਮ ਨੂੰ ਅਲਾਰਮ ਸੈੱਟ ਕਰਨ ਦੀ ਆਗਿਆ ਦੀ ਲੋੜ ਹੈ। ਜੇਕਰ ਇਹ ਆਗਿਆ ਨਹੀਂ ਦਿੱਤੀ ਗਈ ਤਾਂ ਮੌਜੂਦਾ ਅਲਾਰਮ ਵੀ ਕੰਮ ਨਹੀਂ ਕਰਨਗੇ।",
    taskAlarmPermissionDialogCancel = "ਹੁਣ ਨਹੀਂ",
    taskAlarmPermissionDialogConfirm = "ਆਗਿਆ ਦਿਓ",
    notification = "ਨੋਟੀਫਿਕੇਸ਼ਨ",
    alert = "ਰਿੰਗਟੋਨ",
    grantPermission = "ਆਗਿਆ ਦਿਓ",
    permissionsExternalStorageText = { tone ->
        "ਇਹ ਲੱਗਦਾ ਹੈ ਕਿ ਅਸੀਂ $tone ਨਹੀਂ ਚਲਾ ਸਕਦੇ, ਸ਼ਾਇਦ ਕਿਉਂਕਿ ਇੱਕ ਆਗਿਆ ਦੀ ਲੋੜ ਹੈ। ਜੇ ਤੁਸੀਂ ਚਾਹੁੰਦੇ ਹੋ, ਤਾਂ ਤੁਸੀਂ ਆਗਿਆ ਦੇ ਸਕਦੇ ਹੋ। ਬਦਲੇ ਵਿੱਚ, ਇੱਕ ਵੱਖਰਾ ਧੁਨ ਚੁਣੋ। ਇਹ ਫੈਸਲਾ ਸਿਸਟਮ ਸੈਟਿੰਗਜ਼ ਵਿੱਚ ਬਦਲਿਆ ਜਾ ਸਕਦਾ ਹੈ।"
    }
)

private fun questionCountPa(count: Int): String =
    "$count ਸਵਾਲ"
