package com.timilehinaregbesola.mathalarm.utils.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.PT)
val PtMathAlarmStrings = Strings(
    selectAlarmPrompt = "Selecione um alarme ou crie um novo",
    closeAlarmEditor = "Fechar o editor?",
    closeAlarmEditorMessage = "As alterações não salvas neste alarme serão descartadas.",
    discardChanges = "Descartar alterações",

    mathDifficultyNames = listOf("Fácil", "Média", "Difícil", "Personalizada"),
    mathChallengeTitle = "Desafio matemático",
    mixedDifficulty = "Dificuldade mista",
    mixDifficulties = "Misturar dificuldades",
    mathDifficulty = "Dificuldade",
    mathOperations = "Operações",
    addition = "Adição",
    subtraction = "Subtração",
    multiplication = "Multiplicação",
    division = "Divisão",
    additionAndSubtraction = "Adição e subtração",
    multiplicationAndDivision = "Multiplicação e divisão",
    mathExample = "Exemplo",
    refreshExample = "Atualizar",
    applyChallenge = "Aplicar desafio",
    easiestFirst = "Mais fáceis primeiro",
    questions = "Questões",
    chooseRange = "Escolher intervalo",
    checkAnswer = "Verificar resposta",
    nextFeature = "Próximo",
    snoozeAnnouncementTitle = "Adie do seu jeito",
    snoozeAnnouncementDescription = "Defina um limite, escolha uma duração de 1–30 minutos ou desative a soneca. Novos alarmes começam com 3 sonecas de 5 minutos. Os alarmes existentes mantêm seus limites.",
    snoozeAnnouncementInstructions = "Use a caixa Soneca para ativar ou desativar rapidamente. Toque em Editar ao lado para alterar o limite e a duração.",
    whatsNew = "Novidades",
    latestFeatures = "Explore os novos recursos",
    gotIt = "Entendi",
    tryFeature = "Experimentar",
    challengeAnnouncementTitle = "Mais formas de acordar",
    challengeAnnouncementInstructions = "Adicione ou edite um alarme e toque em Editar ao lado de Desafio matemático.",
    exampleChallenge = "Desafio de exemplo",
    exampleDifficultyMix = { easy, medium -> "Fácil: $easy · Média: $medium" },
    challengeAnnouncementDescription = { maximum -> "Resolva até $maximum questões. Misture dificuldades ou crie um desafio personalizado." },
    questionCount = ::questionCountPt,
    challengeSummary = { difficulty, count -> "$difficulty · ${questionCountPt(count)}" },
    mixedQuestionTotal = { count, maximum -> "${questionCountPt(count)} no total · Máximo: $maximum" },
    questionProgress = { current, total -> "Questão $current de $total" },
    questionCountHint = { maximum -> "Escolha de 1 a $maximum. Toque no número para digitar." },
    difficultyQuestionLabel = { difficulty -> "Questões: $difficulty" },
    decreaseQuestionCount = { label -> "Diminuir quantidade: $label" },
    increaseQuestionCount = { label -> "Aumentar quantidade: $label" },
    alarmScheduleFailed = "Não foi possível agendar o alarme. Salve novamente.",
    alarmSaveFailed = "Não foi possível salvar o alarme. Tente novamente.",
    alarmUpdateFailed = "Não foi possível atualizar o alarme. Tente novamente.",
    alarmDismissFailed = "Não foi possível parar o alarme. Tente novamente.",
    alarmSnoozeFailed = "Não foi possível adiar o alarme. Tente novamente.",
    incorrectAnswer = "Resposta incorreta. Tente novamente.",
    multipleDays = "Múltiplos dias",
    greeting = { hour ->
        when {
            hour < 12 -> "Bom dia"
            hour in 12..17 -> "Boa tarde"
            else -> "Boa noite"
        }
    },
    expand = "Expandir",
    delete = "Excluir",
    edit = "Editar",
    dateLocale = "pt",
    skipAnnouncementDescription = "Faça uma pausa no próximo alarme sem alterar o resto da programação.",
    skipAnnouncementInstructions = "Expanda um alarme ativado e toque em Ignorar próximo. Disponível para alarmes semanais e alarmes com vários dias selecionados.",
    skipAnnouncementUndo = "Apenas a próxima ocorrência é ignorada. Os alarmes semanais voltam na semana seguinte; os que não se repetem mantêm as datas restantes. Toque em Desfazer antes da hora ignorada para restaurá-la. Os alarmes adiados e os outros alarmes continuam programados.",
    viewAlarms = "Ver alarmes",
    skipAnnouncementExample = "Experimente este exemplo",
    skipNext = "Ignorar próximo",
    skippedAlarmOn = { date -> "Ignorado · $date" },
    undo = "Desfazer",
    undoSkip = "Desfazer omissão",
    collapse = "Colapso",
    noUpcomingAlarms = "Nenhuma alarme próximo",
    nextAlarmText = "Próximo alarme:",
    nextOccurrenceOn = { date -> "Próximo: $date" },
    nextAlarmIn = { hours, minutes ->
        if (hours == 0 && minutes == 0) "Próximo alarme em menos de um minuto"
        else "Próximo alarme em " + listOfNotNull(
            if (hours > 0) "$hours ${if (hours == 1) "hora" else "horas"}" else null,
            if (minutes > 0) "$minutes ${if (minutes == 1) "minuto" else "minutos"}" else null,
        ).joinToString(" ")
    },
    alarmSet = "Alarme definido para",
    alarmPermissionDialogConfirm = "Confirmar",
    alarmPermissionDialogCancel = "Cancelar",
    alarmPermissionDialogText = "Este aplicativo requer permissão para definir alarmes.",
    alarmPermissionDialogTitle = "Permissão necessária",
    clearAlarmDialogConfirm = "Confirmar",
    clearAlarmDialogCancel = "Cancelar",
    clearAlarmDialogText = "Tem certeza de que deseja limpar os alarmes?",
    clearAlarmDialogTitle = "Limpar alarmes",
    emptyAlarmList = "Lista de alarmes vazia",
    nothingToSee = "Nada para ver aqui",
    alarms = "Alarmes",
    deleteAll = "Excluir tudo",
    settings = "Configurações",
    toneUnavailable = "Tom indisponível",
    clear = "Claro",
    maximumSnoozes = "Máximo de adiamentos",
    unlimitedSnoozes = "Sem limite",
    noSnoozesLeft = "Não restam adiamentos",
    snoozesLeft = { count -> "Restam $count adiamentos" },
    snoozeLimitSummary = { count, minutes -> "$count adiamentos · até $minutes minutos extras" },
    snoozeOff = "Desativado",
    allowSnooze = "Permitir adiar",
    snoozeDuration = "Duração (minutos)",
    snoozeDurationHint = "Escolha de 1 a 30 minutos. Toque no número para digitar.",
    applySnooze = "Aplicar configurações",
    snoozeMaximumSummary = { count -> "Máximo $count" },
    snoozeSettingsSummary = { minutes, limit -> "$minutes min · $limit" },
    snooze = "Soneca",
    enter = "Entrar",
    noRingtonePicker = "Seleção de toque indisponível",
    alarmTitle = "Título do alarme",
    goodDay = "Bom dia",
    defaultAlarmTone = "Tom de alarme padrão",
    disabledNotificationMessage = "Notificações estão desativadas para este aplicativo.",
    ok = "OK",
    notificationPermissionDialogMessage = "Este aplicativo requer permissão para exibir notificações.",
    repeatWeekly = "Repetir semanalmente",
    vibrate = "Vibrar",
    testAlarm = "Testar alarme",
    save = "Salvar",
    easyMath = "Matemática fácil",
    mediumMath = "Matemática média",
    hardMath = "Matemática difícil",
    selectHour = "Selecione a hora",
    cancel = "Cancelar",
    input = "Entrada",
    picker = "Seletor",
    system = "Sistema",
    dark = "Escuro",
    light = "Claro",
    appSettings = "Configurações do aplicativo",
    back = "Voltar",
    colorTheme = "Tema de cor",
    alarmOrder = "Ordem dos alarmes",
    alarmOrderDescription = "Escolha se os alarmes aparecem pela ordem de criacao ou pelo horario em que tocam.",
    creationOrder = "Ordem de criação",
    timeOrder = "Hora",
    help = "Ajuda",
    sendFeedback = "Enviar feedback",
    sendFeedbackMessage = "Enviar feedback para o desenvolvedor",
    supportEmail = "aregbestimi@gmail.com",
    emailChooserTitle = "Escolha um aplicativo de e-mail",
    shareMathAlarm = "Compartilhar MathAlarm",
    shareWithOthers = "Compartilhar com outros",
    taskAlarmPermissionDialogText = "Para que os alarmes funcionem, o alarme matemático precisa de permissão para definir alarmes. Se esta permissão não for concedida, os alarmes existentes não funcionarão tão bem.",
    alert = "Alerta",
    share = "Compartilhar",
    defaultSendText = "Alarme padrão",
    disabledNotificationMessageExtended = "Notificações deste aplicativo estão desativadas. Por favor, vá para as configurações do seu dispositivo e ative-as.",
    grantPermission = "Permitir",
    notification = "Notificação",
    permissionsExternalStorageText = {  tone ->
        "Parece que não podemos tocar $tone, provavelmente porque é necessária permissão. Se desejar, você pode conceder a permissão. Como alternativa, selecione um som diferente. Esta decisão pode ser alterada nas configurações do sistema."
    },
    taskAlarmPermissionDialogCancel = "Agora não",
    taskAlarmPermissionDialogConfirm = "Conceder"

)

private fun questionCountPt(count: Int): String =
    if (count == 1) "$count questão" else "$count questões"
