package com.timilehinaregbesola.mathalarm.utils.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.RU)
val RuMathAlarmStrings = Strings(
    mathDifficultyNames = listOf("Легко", "Средне", "Сложно", "Своя настройка"),
    mathChallengeTitle = "Математическое задание",
    mixedDifficulty = "Разная сложность",
    mixDifficulties = "Смешать уровни сложности",
    mathDifficulty = "Сложность",
    mathOperations = "Операции",
    addition = "Сложение",
    subtraction = "Вычитание",
    multiplication = "Умножение",
    division = "Деление",
    additionAndSubtraction = "Сложение и вычитание",
    multiplicationAndDivision = "Умножение и деление",
    mathExample = "Пример",
    refreshExample = "Обновить",
    applyChallenge = "Применить задание",
    easiestFirst = "Сначала простые",
    questions = "Вопросы",
    chooseRange = "Выбрать диапазон",
    checkAnswer = "Проверить ответ",
    whatsNew = "Что нового",
    latestFeatures = "Узнайте о новых функциях",
    gotIt = "Понятно",
    tryFeature = "Попробовать",
    challengeAnnouncementTitle = "Больше способов проснуться",
    challengeAnnouncementInstructions = "Добавьте или измените будильник и нажмите «Редактировать» рядом с математическим заданием.",
    exampleChallenge = "Пример задания",
    questionCount = ::questionCountRu,
    challengeSummary = { difficulty, count -> "$difficulty · ${questionCountRu(count)}" },
    mixedQuestionTotal = { count, maximum -> "Всего: ${questionCountRu(count)} · Максимум: $maximum" },
    questionProgress = { current, total -> "Вопрос $current из $total" },
    questionCountHint = { maximum -> "Выберите от 1 до $maximum. Нажмите на число для ввода." },
    difficultyQuestionLabel = { difficulty -> "Вопросы — $difficulty" },
    decreaseQuestionCount = { label -> "Уменьшить количество: $label" },
    increaseQuestionCount = { label -> "Увеличить количество: $label" },
    exampleDifficultyMix = { easy, medium -> "Легко: $easy · Средне: $medium" },
    challengeAnnouncementDescription = { maximum -> "Решайте до $maximum вопросов. Смешивайте уровни сложности или создайте своё задание." },
    alarmScheduleFailed = "Не удалось установить будильник. Сохраните его ещё раз.",
    alarmSaveFailed = "Не удалось сохранить будильник. Повторите попытку.",
    alarmUpdateFailed = "Не удалось обновить будильник. Повторите попытку.",
    alarmDismissFailed = "Не удалось остановить будильник. Повторите попытку.",
    alarmSnoozeFailed = "Не удалось отложить будильник. Повторите попытку.",
    incorrectAnswer = "Неверный ответ. Попробуйте ещё раз.",
    multipleDays = "Несколько дней",
    greeting = { hour ->
        when {
            hour < 12 -> "Доброе утро"
            hour in 12..17 -> "Добрый день"
            else -> "Добрый вечер"
        }
    },
    expand = "Развернуть",
    delete = "Удалить",
    edit = "Редактировать",
    collapse = "Свернуть",
    noUpcomingAlarms = "Нет предстоящих будильников",
    nextAlarmText = "Следующий будильник через",
    alarmSet = "Будильник установлен на",
    alarmPermissionDialogConfirm = "Подтвердить",
    alarmPermissionDialogCancel = "Отмена",
    alarmPermissionDialogText = "Это приложение требует разрешения на установку будильников.",
    alarmPermissionDialogTitle = "Требуется разрешение",
    clearAlarmDialogConfirm = "Подтвердить",
    clearAlarmDialogCancel = "Отмена",
    clearAlarmDialogText = "Вы уверены, что хотите сбросить сигналы тревоги?",
    clearAlarmDialogTitle = "Удалить будильник",
    emptyAlarmList = "Пустой список будильников",
    nothingToSee = "Здесь ничего нет",
    alarms = "Будильники",
    deleteAll = "Удалить все",
    settings = "Настройки",
    toneUnavailable = "Тон недоступен",
    clear = "Очистить",
    snooze = "Отложить",
    enter = "Ввод",
    noRingtonePicker = "Выбор мелодии звонка недоступен",
    alarmTitle = "Название будильника",
    goodDay = "Хороший день",
    defaultAlarmTone = "Мелодия будильника (по умолчанию)",
    disabledNotificationMessage = "Уведомления отключены для этого приложения.",
    disabledNotificationMessageExtended = "Уведомления этого приложения отключены. Пожалуйста, перейдите в настройки вашего устройства и включите их.",
    ok = "хорошо",
    notificationPermissionDialogMessage = "Это приложение требует разрешения на отображение уведомлений.",
    repeatWeekly = "Повторять еженедельно",
    vibrate = "Вибрация",
    testAlarm = "Тестовый будильник",
    save = "Сохранить",
    easyMath = "Простая математика",
    mediumMath = "Средняя математика",
    hardMath = "Сложная математика",
    selectHour = "Выберите час",
    cancel = "Отмена",
    input = "Ввод",
    picker = "Выбор",
    system = "Система",
    dark = "Темный",
    light = "Светлый",
    appSettings = "Настройки приложения",
    back = "Назад",
    colorTheme = "Цветовая тема",
    alarmOrder = "Порядок будильников",
    alarmOrderDescription = "Выберите, показывать будильники по порядку создания или по времени срабатывания.",
    creationOrder = "По порядку создания",
    timeOrder = "По времени",
    help = "Помощь",
    sendFeedback = "Отправить отзыв",
    sendFeedbackMessage = "Отправить отзыв разработчику",
    supportEmail = "aregbestimi@gmail.com",
    emailChooserTitle = "Выбор почты",
    shareMathAlarm = "Поделиться MathAlarm",
    shareWithOthers = "Поделиться с другими",
    share = "Поделиться",
    alert = "Предупреждение",
    defaultSendText = "Стандартный будильник",
    taskAlarmPermissionDialogText = "Чтобы сигналы тревоги работали, Math Alarm необходимо разрешение на установку сигналов тревоги. Если это разрешение не предоставлено, существующие сигналы тревоги также не будут работать.",
    taskAlarmPermissionDialogConfirm = "Подтвердить",
    grantPermission = "Разрешить",
    notification = "Уведомление",
    taskAlarmPermissionDialogCancel = "Не сейчас",
    permissionsExternalStorageText = { tone ->
        "Кажется, мы не можем воспроизвести $tone, возможно, потому, что требуется разрешение. Если хотите, можете дать разрешение. Либо выберите другой звук. Это решение можно изменить в настройках системы."
    }
)

private fun questionCountRu(count: Int): String =
    when {
        count % 10 == 1 && count % 100 != 11 -> "$count вопрос"
        count % 10 in 2..4 && count % 100 !in 12..14 -> "$count вопроса"
        else -> "$count вопросов"
    }
