package com.timilehinaregbesola.mathalarm.utils.strings

data class Strings(
    val mathDifficultyNames: List<String>,
    val mathChallengeTitle: String,
    val mixedDifficulty: String,
    val mixDifficulties: String,
    val mathDifficulty: String,
    val mathOperations: String,
    val addition: String,
    val subtraction: String,
    val multiplication: String,
    val division: String,
    val additionAndSubtraction: String,
    val multiplicationAndDivision: String,
    val mathExample: String,
    val refreshExample: String,
    val applyChallenge: String,
    val easiestFirst: String,
    val questions: String,
    val chooseRange: String,
    val checkAnswer: String,
    val nextFeature: String,
    val whatsNew: String,
    val latestFeatures: String,
    val gotIt: String,
    val tryFeature: String,
    val challengeAnnouncementTitle: String,
    val challengeAnnouncementInstructions: String,
    val exampleChallenge: String,
    val exampleDifficultyMix: (easy: Int, medium: Int) -> String,
    val challengeAnnouncementDescription: (maximum: Int) -> String,
    val questionCount: (count: Int) -> String,
    val challengeSummary: (difficulty: String, count: Int) -> String,
    val mixedQuestionTotal: (count: Int, maximum: Int) -> String,
    val questionProgress: (current: Int, total: Int) -> String,
    val questionCountHint: (maximum: Int) -> String,
    val difficultyQuestionLabel: (difficulty: String) -> String,
    val decreaseQuestionCount: (label: String) -> String,
    val increaseQuestionCount: (label: String) -> String,
    val alarmScheduleFailed: String,
    val alarmSaveFailed: String,
    val alarmUpdateFailed: String,
    val alarmDismissFailed: String,
    val alarmSnoozeFailed: String,
    val incorrectAnswer: String,
    val multipleDays: String,
    val greeting: (hour: Int) -> String,
    val expand: String,
    val delete: String,
    val edit: String,
    val dateLocale: String,
    val skipNext: String,
    val skipAnnouncementDescription: String,
    val skipAnnouncementInstructions: String,
    val skipAnnouncementUndo: String,
    val viewAlarms: String,
    val skipAnnouncementExample: String,
    val skippedAlarmOn: (date: String) -> String,
    val undoSkip: String,
    val undo: String,
    val collapse: String,
    val noUpcomingAlarms: String,
    val nextAlarmText: String,
    val nextOccurrenceOn: (date: String) -> String,
    val nextAlarmIn: (hours: Int, minutes: Int) -> String,
    val alarmSet: String,
    val alarmPermissionDialogConfirm: String,
    val alarmPermissionDialogCancel: String,
    val alarmPermissionDialogText: String,
    val alarmPermissionDialogTitle: String,
    val clearAlarmDialogConfirm: String,
    val clearAlarmDialogCancel: String,
    val clearAlarmDialogText: String,
    val clearAlarmDialogTitle: String,
    val emptyAlarmList: String,
    val nothingToSee: String,
    val alarms: String,
    val deleteAll: String,
    val settings: String,
    val toneUnavailable: String,
    val clear: String,
    val snooze: String,
    val enter: String,
    val noRingtonePicker: String,
    val alarmTitle: String,
    val goodDay: String,
    val defaultAlarmTone: String,
    val disabledNotificationMessage: String,
    val disabledNotificationMessageExtended: String,
    val ok: String,
    val notificationPermissionDialogMessage: String,
    val repeatWeekly: String,
    val vibrate: String,
    val testAlarm: String,
    val save: String,
    val easyMath: String,
    val mediumMath: String,
    val hardMath: String,
    val selectHour: String,
    val cancel: String,
    val input: String,
    val picker: String,
    val system: String,
    val dark: String,
    val light: String,
    val appSettings: String,
    val back: String,
    val colorTheme: String,
    val alarmOrder: String,
    val alarmOrderDescription: String,
    val creationOrder: String,
    val timeOrder: String,
    val help: String,
    val sendFeedback: String,
    val sendFeedbackMessage: String,
    val supportEmail: String,
    val emailChooserTitle: String,
    val shareMathAlarm: String,
    val shareWithOthers: String,
    val share: String,
    val defaultSendText: String,
    val taskAlarmPermissionDialogText: String,
    val taskAlarmPermissionDialogConfirm: String,
    val taskAlarmPermissionDialogCancel: String,
    val notification: String,
    val alert: String,
    val grantPermission: String,
    val permissionsExternalStorageText: (tone: String) -> String,
)

object Locales {
    const val EN = "en"
    const val ES = "es"
    const val DE = "de"
    const val RU = "ru"
    const val PT = "pt"
    const val HI = "hi"
    const val PA = "pa"
    const val BN = "bn"
    const val ZH = "zh"
}
