package com.timilehinaregbesola.mathalarm.utils.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.ZH)
val ZhMathAlarmStrings = Strings(
    mathDifficultyNames = listOf("简单", "中等", "困难", "自定义"),
    mathChallengeTitle = "数学挑战",
    mixedDifficulty = "混合难度",
    mixDifficulties = "混合难度",
    mathDifficulty = "难度",
    mathOperations = "运算",
    addition = "加法",
    subtraction = "减法",
    multiplication = "乘法",
    division = "除法",
    additionAndSubtraction = "加法和减法",
    multiplicationAndDivision = "乘法和除法",
    mathExample = "示例",
    refreshExample = "换一个",
    applyChallenge = "应用挑战",
    easiestFirst = "从易到难",
    questions = "题目",
    chooseRange = "选择范围",
    checkAnswer = "检查答案",
    nextFeature = "下一项",
    whatsNew = "新功能",
    latestFeatures = "了解最新功能",
    gotIt = "知道了",
    tryFeature = "试试看",
    challengeAnnouncementTitle = "更多唤醒方式",
    challengeAnnouncementInstructions = "添加或编辑闹钟，然后点按数学挑战旁的“编辑”。",
    exampleChallenge = "挑战示例",
    exampleDifficultyMix = { easy, medium -> "简单：${easy} · 中等：${medium}" },
    challengeAnnouncementDescription = { maximum -> "最多解答${maximum}道题。混合不同难度，或创建适合自己的挑战。" },
    questionCount = ::questionCountZh,
    challengeSummary = { difficulty, count -> "$difficulty · ${questionCountZh(count)}" },
    mixedQuestionTotal = { count, maximum -> "共${questionCountZh(count)} · 最多${maximum}道" },
    questionProgress = { current, total -> "第${current}题，共${total}题" },
    questionCountHint = { maximum -> "选择1–${maximum}。点按数字即可输入。" },
    difficultyQuestionLabel = { difficulty -> "题目：${difficulty}" },
    decreaseQuestionCount = { label -> "减少数量：${label}" },
    increaseQuestionCount = { label -> "增加数量：${label}" },
    alarmScheduleFailed = "无法设置闹钟，请重新保存。",
    alarmSaveFailed = "无法保存闹钟，请重试。",
    alarmUpdateFailed = "无法更新闹钟，请重试。",
    alarmDismissFailed = "无法关闭闹钟，请重试。",
    alarmSnoozeFailed = "无法稍后提醒，请重试。",
    incorrectAnswer = "答案错误，请重试。",
    multipleDays = "多天",
    greeting = { hour ->
        when {
            hour < 12 -> "早上好"
            hour in 12..17 -> "下午好"
            else -> "晚上好"
        }
    },
    expand = "展开",
    delete = "删除",
    edit = "编辑",
    dateLocale = "zh",
    skipAnnouncementDescription = "跳过下一次闹钟，而不更改其余日程。",
    skipAnnouncementInstructions = "展开已开启的闹钟，然后点按“跳过下一个”。适用于每周重复的闹钟和选择了多天的闹钟。",
    skipAnnouncementUndo = "只跳过下一次响铃。每周闹钟会在下一周恢复；不重复的闹钟会保留剩余日期。在被跳过的时间之前点按“撤销”即可恢复。贪睡提醒和其他闹钟仍按计划响铃。",
    viewAlarms = "查看闹钟",
    skipAnnouncementExample = "试试这个示例",
    skipNext = "跳过下一个",
    skippedAlarmOn = { date -> "已跳过 · $date" },
    undo = "撤销",
    undoSkip = "撤销跳过",
    collapse = "折叠",
    noUpcomingAlarms = "没有即将到来的闹钟",
    nextAlarmText = "下一个闹钟：",
    nextOccurrenceOn = { date -> "下次：$date" },
    nextAlarmIn = { hours, minutes ->
        if (hours == 0 && minutes == 0) "下一个闹钟将在不到一分钟后响起"
        else "下一个闹钟将在" + listOfNotNull(
            if (hours > 0) "${hours}小时" else null,
            if (minutes > 0) "${minutes}分钟" else null,
        ).joinToString("") + "后响起"
    },
    alarmSet = "闹钟已设置",
    alarmPermissionDialogConfirm = "确认",
    alarmPermissionDialogCancel = "取消",
    alarmPermissionDialogText = "此应用需要设置闹钟的权限。",
    alarmPermissionDialogTitle = "需要权限",
    clearAlarmDialogConfirm = "确认",
    clearAlarmDialogCancel = "取消",
    clearAlarmDialogText = "您確定要清除警報嗎？",
    clearAlarmDialogTitle = "清除闹钟",
    emptyAlarmList = "空闹钟列表",
    nothingToSee = "这里什么都没有",
    alarms = "闹钟",
    deleteAll = "删除所有",
    settings = "设置",
    toneUnavailable = "铃声不可用",
    clear = "清除",
    snooze = "贪睡",
    enter = "输入",
    noRingtonePicker = "没有铃声选择器",
    alarmTitle = "闹钟标题",
    goodDay = "祝你有个好日子",
    defaultAlarmTone = "默认闹钟铃声",
    disabledNotificationMessage = "此应用的通知已被禁用。",
    disabledNotificationMessageExtended = "此应用的通知已被禁用。请到您的设备设置中启用它们。",
    ok = "确定",
    notificationPermissionDialogMessage = "此应用需要显示通知的权限。",
    repeatWeekly = "每周重复",
    vibrate = "振动",
    testAlarm = "测试闹钟",
    save = "保存",
    easyMath = "简单数学",
    mediumMath = "中等数学",
    hardMath = "困难数学",
    selectHour = "选择小时",
    cancel = "取消",
    input = "输入",
    picker = "选择器",
    system = "系统",
    dark = "深色",
    light = "浅色",
    appSettings = "应用设置",
    back = "返回",
    colorTheme = "颜色主题",
    alarmOrder = "闹钟排序",
    alarmOrderDescription = "选择按创建顺序显示闹钟，或按响铃时间显示闹钟。",
    creationOrder = "创建顺序",
    timeOrder = "时间",
    help = "帮助",
    sendFeedback = "发送反馈",
    sendFeedbackMessage = "向开发者发送反馈",
    supportEmail = "aregbestimi@gmail.com",
    emailChooserTitle = "发送电子邮件",
    defaultSendText = "默认闹钟",
    shareMathAlarm = "分享数学闹钟",
    shareWithOthers = "看看这个很酷的闹钟应用",
    share = "分享",
    taskAlarmPermissionDialogText = "为了使闹钟正常工作，数学闹钟需要设置闹钟的权限。如果未授予此权限，现有的闹钟也将无法工作。",
    taskAlarmPermissionDialogCancel = "暂不",
    taskAlarmPermissionDialogConfirm = "授予",
    notification = "通知",
    alert = "铃声",
    grantPermission = "授予权限",
    permissionsExternalStorageText = { tone ->
        "我们似乎无法播放$tone，可能是因为需要权限。如果您愿意，您可以授予权限。或者，选择不同的声音。这个决定可以在系统设置中更改。"
    }
)

private fun questionCountZh(count: Int): String =
    "${count}道题"
